### ISSUE TITLE
[ISSUE]: The footer section of the website is not working correctly

### ISSUE THREAD

**Issue by TiwariSimona** [hackclubiter/hackclubiter.github.io#52] opened 2021-09-17 07:44 UTC
While clicking on the 'Workshops' and 'Projects' section at the footer of the website, it is taking us back to the home page of the website instead of the respective sections.

I can work on the fix, you can assign the issue to me.

**Comment by arpanaditya** [comment] 2021-09-17 12:49
I have fixed this issue before already. You can refer to PR #51 Just waiting for a merge. 
You can close this issue @TiwariSimona

**Comment by Saswat7101** [comment] 2021-09-17 12:54
Yes, this has been dealt with already by @arpanaditya.

And also a piece of advice to @TiwariSimona, before adding any issues check if the issue is already created or it has been assigned to anyone

**Closed as completed by Saswat7101** 2021-09-17 12:54 UTC
Labels: feature-request
